package org.omg.PortableServer;


/**
* org/omg/PortableServer/REQUEST_PROCESSING_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../../../../src/share/classes/org/omg/PortableServer/poa.idl
* Monday, November 10, 2008 6:32:12 AM GMT
*/

public interface REQUEST_PROCESSING_POLICY_ID
{

  /**
	 * The value representing REQUEST_PROCESSING_POLICY_ID.
	 */
  public static final int value = (int)(22);
}
